name: Deploy Flask App to Azure Web App - Approverapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_501A5DAC4B5941378B75B234453568CD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E8F0F13E72794357AE47A88EDD473097 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A31806BF85C44B3687AD170350FEEADB }}

      # 5️⃣ Copy all app files to persistent wwwroot
      - name: Copy files to /home/site/wwwroot
        run: |
          echo "Copying all app files to persistent wwwroot..."
          mkdir -p /home/site/wwwroot
          cp -r $(pwd)/* /home/site/wwwroot/
          ls -l /home/site/wwwroot/  # Optional: list files to verify

      # 6️⃣ Restart Web App to pick up changes
      - name: Restart Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Approverapp'
          slot-name: 'Production'
          package: '/home/site/wwwroot'  # Use copied files
